version: '3.8'

services:
  cliente:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zuma_frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0

networks:
  default:
    name: zuma_network