services:
  cliente:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: zuma_frontend
    ports:
      - "5174:5173"  # Cambio de puerto para evitar conflicto
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://laravel_nginx  # URL del backend Laravel
    restart: unless-stopped
    command: npm run dev -- --host 0.0.0.0
    networks:
      - laravel_red_2025

networks:
  laravel_red_2025:
    external: true